language: c
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - lib32asound2
      - lib32z1
      - lib32bz2-1.0
      - libssl1.0.0:i386
      - libfreetype6:i386
services: 
  - mongodb
script: 
  - scripts/run-tests.sh
env:
  - PHARO_VERSION=50
  - PHARO_VERSION=40
  - PHARO_VERSION=30