language: smalltalk
sudo: required
os:
  - linux
#  - osx

before_install:
  - bash .install_mongodb_on_travis.sh
  - sleep 15  # https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections
  - mongo --eval 'db.version();'
  - bash .install_arangodb.sh

matrix:
  include:
    - smalltalk: Pharo-7.0
      smalltalk_config: .smalltalk.ston
      env: MONGODB=3.2
    - smalltalk: Pharo64-7.0
      smalltalk_config: .smalltalk.ston
      env: MONGODB=3.2
    - smalltalk: Pharo-7.0
      smalltalk_config: .smalltalk.ston
      env: MONGODB=3.4
    - smalltalk: Pharo64-7.0
      smalltalk_config: .smalltalk.ston
      env: MONGODB=3.4
    - smalltalk: Pharo-7.0
      smalltalk_config: .smalltalk.ston
      env: MONGODB=3.6
    - smalltalk: Pharo64-7.0
      smalltalk_config: .smalltalk.ston
      env: MONGODB=3.6
    - smalltalk: Pharo-7.0
      smalltalk_config: .smalltalk.ston
      env: MONGODB=4.0
    - smalltalk: Pharo64-7.0
      smalltalk_config: .smalltalk.ston
      env: MONGODB=4.0
# disabling unqlite for now as there is a FFI problem preventing unqlite lib zu work
# Esteban will fix that later when the right vm is there
#    - smalltalk: Pharo-7.0
#      before_script: wget https://github.com/pharo-nosql/PunQLite/releases/download/stable/unqlite.so
#      smalltalk_config: .smalltalk-unqlite.ston
    - smalltalk: Pharo-7.0
      smalltalk_config: .smalltalk-multiple.ston
      env: MONGODB=3.4
    - smalltalk: Pharo64-7.0
      smalltalk_config: .smalltalk-multiple.ston
      env: MONGODB=3.4
    - smalltalk: Pharo-6.1
      smalltalk_config: .smalltalk.ston
      env: MONGODB=3.4
#    - smalltalk: Pharo-6.1
#      before_script: wget https://github.com/pharo-nosql/PunQLite/releases/download/stable/unqlite.so
#      smalltalk_config: .smalltalk-unqlite.ston

# bob-bench xUnit file analysis (?where is my xml?)
after_script:
 - pip install --user benchupload && python -mbenchupload
